// =========================
// 🔵 DETECÇÃO DE POLÍTICA
// =========================
export const politicalKeywords = [
    "prefeito",
    "vereador",
    "deputado",
    "senador",
    "governador",
    "presidente",
    "campanha",
    "eleição",
    "eleições",
    "voto",
    "votar",
    "mandato",
    "governo",
    "gestão",
    "política",
    "político",
    "políticos",
    "cidade",
    "bairro",
    "população",
    "comunidade",
    "projeto",
    "lei",
    "proposta",
    "reforma",
    "administração pública",
    "serviço público",
    "licitação",
    "transparência",
    "corrupção",
    "imposto",
    "taxa",
    "benefício",
    "programa social",
    "obra pública",
    "inauguração",
    "esquerda",
    "centrão",
    "direita",
    "presidente",
    "lula",
    "bolsonaro",
    "pt",
    "pl",
    "psol",
    "psbd",
    "petista",
    "bolsonarista",
    "pmdb",
    "uniao brasil",
    "kin kataguiri",
    "missão brasil",
    "mbl",

  ];
  
  
  // =========================
  // 🟢 POSITIVO POLÍTICO
  // =========================
  export const politicalPositiveWords = [
    "aprovado",
    "aprovada",
    "melhorou",
    "melhoria",
    "avanço",
    "avanços",
    "conquista",
    "conquistas",
    "resultado",
    "resultados",
    "entregue",
    "entregou",
    "entregando",
    "inaugurado",
    "inauguração",
    "construído",
    "realizado",
    "realizou",
    "cumpriu",
    "cumprindo",
    "promessa cumprida",
    "trabalho sério",
    "boa gestão",
    "excelente gestão",
    "ótimo trabalho",
    "parabéns",
    "orgulho",
    "competente",
    "responsável",
    "eficiente",
    "transparente",
    "honesto",
    "honestidade",
    "compromisso",
    "comprometido",
    "investimento",
    "investiu",
    "crescimento",
    "desenvolvimento",
    "progresso",
    "evolução",
    "melhor prefeito",
    "melhor gestão",
    "apoio",
    "apoio total",
    "tem meu apoio",
    "tem meu voto",
    "me representa",
    "representa bem",
    "continua assim",
    "segue firme",
    "tamo junto",
    "juntos",
    "fez muito",
    "fez bastante",
    "trabalhando",
    "trabalho incrível",
  ];
  
  
  // =========================
  // 🔴 NEGATIVO POLÍTICO
  // =========================
  export const politicalNegativeWords = [
    "corrupção",
    "corrupto",
    "roubo",
    "roubou",
    "ladrão",
    "desvio",
    "desviou",
    "fraude",
    "escândalo",
    "vergonha",
    "absurdo",
    "ridículo",
    "péssimo",
    "piorou",
    "pior gestão",
    "incompetente",
    "incapaz",
    "irresponsável",
    "mentira",
    "mentiroso",
    "promessa não cumprida",
    "não cumpriu",
    "enganou",
    "enganação",
    "abandono",
    "abandono da cidade",
    "descaso",
    "falta de respeito",
    "falta de compromisso",
    "não fez nada",
    "não fez",
    "não trabalha",
    "não resolve",
    "problema",
    "problemas",
    "caos",
    "crise",
    "sujeira",
    "buraco",
    "falta",
    "falta tudo",
    "sem saúde",
    "sem segurança",
    "sem educação",
    "violência",
    "aumentou imposto",
    "taxa alta",
    "caro",
    "gasto público",
    "desperdício",
    "má gestão",
    "fora",
    "fora prefeito",
    "fora governo",
    "não voto",
    "nunca mais voto",
    "perdeu meu voto",
    "não me representa",
    "decepção",
    "decepcionante",
    "triste",
    "lamentável",
    "indignado",
    "indignação",
  ];